version: '3.1'

services:
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - docker.env
    networks:
      - mysql

networks:
  mysql:
    driver: bridge
